const http = require('http');


let users = [{ "id": 1, "name": "Urson", "place": "914 Farwell Hill" },
{ "id": 2, "name": "Consuelo", "place": "9291 Kipling Lane" },
{ "id": 3, "name": "Roxane", "place": "8055 Stoughton Pass" },
{ "id": 4, "name": "Byrle", "place": "07888 Menomonie Junction" },
{ "id": 5, "name": "Harwell", "place": "989 Becker Parkway" },
{ "id": 6, "name": "Gwyn", "place": "8 Pennsylvania Way" },
{ "id": 7, "name": "Kiersten", "place": "5 Valley Edge Point" },
{ "id": 8, "name": "Jemmie", "place": "236 Ronald Regan Drive" },
{ "id": 9, "name": "Armand", "place": "6350 Ronald Regan Lane" },
{ "id": 10, "name": "Anjanette", "place": "68152 Holy Cross Hill" },
{ "id": 11, "name": "Nikkie", "place": "27 Artisan Hill" },
{ "id": 12, "name": "Rozella", "place": "5361 South Court" },
{ "id": 13, "name": "Cullin", "place": "45 Gulseth Parkway" },
{ "id": 14, "name": "Ardelia", "place": "366 Dorton Park" },
{ "id": 15, "name": "Norene", "place": "91035 Holy Cross Point" },
{ "id": 16, "name": "Angel", "place": "35512 Pawling Lane" },
{ "id": 17, "name": "Irene", "place": "2 Russell Circle" },
{ "id": 18, "name": "Charyl", "place": "686 Sauthoff Circle" },
{ "id": 19, "name": "Vikki", "place": "85 Bluejay Road" },
{ "id": 20, "name": "Nevile", "place": "8100 Mariners Cove Plaza" },
{ "id": 21, "name": "Arleyne", "place": "49 Schlimgen Court" },
{ "id": 22, "name": "Page", "place": "8 Derek Crossing" },
{ "id": 23, "name": "Alick", "place": "757 Hansons Pass" },
{ "id": 24, "name": "Annabela", "place": "8 Washington Parkway" },
{ "id": 25, "name": "Xylina", "place": "64 Green Ridge Place" },
{ "id": 26, "name": "Felice", "place": "449 Homewood Plaza" },
{ "id": 27, "name": "Forrester", "place": "86694 Prentice Street" },
{ "id": 28, "name": "Quent", "place": "5334 Fair Oaks Trail" },
{ "id": 29, "name": "Gram", "place": "2438 Elka Circle" },
{ "id": 30, "name": "Nathan", "place": "93 Gale Pass" },
{ "id": 31, "name": "Dorise", "place": "5 Mayfield Avenue" },
{ "id": 32, "name": "Grantham", "place": "4 Helena Street" },
{ "id": 33, "name": "Piotr", "place": "13 Brown Place" },
{ "id": 34, "name": "Powell", "place": "0 Memorial Center" },
{ "id": 35, "name": "Jaquenetta", "place": "6264 Spaight Avenue" },
{ "id": 36, "name": "Fernando", "place": "8213 Michigan Lane" },
{ "id": 37, "name": "Christopher", "place": "4 Dennis Street" },
{ "id": 38, "name": "Emmery", "place": "7508 Fairview Plaza" },
{ "id": 39, "name": "Edlin", "place": "59837 Leroy Place" },
{ "id": 40, "name": "Christie", "place": "2 Buell Trail" },
{ "id": 41, "name": "Mariann", "place": "743 New Castle Park" },
{ "id": 42, "name": "North", "place": "5132 Morrow Hill" },
{ "id": 43, "name": "Goddard", "place": "2 Bluestem Lane" },
{ "id": 44, "name": "Uri", "place": "15 Eggendart Park" },
{ "id": 45, "name": "Corena", "place": "44 Hoard Way" },
{ "id": 46, "name": "Levy", "place": "0150 Merry Place" },
{ "id": 47, "name": "Olly", "place": "8 Corscot Terrace" },
{ "id": 48, "name": "Hillel", "place": "52173 Moulton Park" },
{ "id": 49, "name": "Samuele", "place": "429 Garrison Lane" },
{ "id": 50, "name": "Adiana", "place": "7 Waywood Circle" },
{ "id": 51, "name": "Rodrick", "place": "517 Ruskin Crossing" },
{ "id": 52, "name": "Marjie", "place": "95878 Stone Corner Hill" },
{ "id": 53, "name": "Nollie", "place": "405 Arizona Trail" },
{ "id": 54, "name": "Oswald", "place": "57 Maple Plaza" },
{ "id": 55, "name": "Onofredo", "place": "16948 Jay Court" },
{ "id": 56, "name": "Devlin", "place": "3216 Hazelcrest Terrace" },
{ "id": 57, "name": "Gaspard", "place": "445 Park Meadow Way" },
{ "id": 58, "name": "Lotta", "place": "9193 Green Drive" },
{ "id": 59, "name": "Rudolf", "place": "80764 Springview Park" },
{ "id": 60, "name": "Cthrine", "place": "904 Grasskamp Center" },
{ "id": 61, "name": "Coral", "place": "345 Little Fleur Lane" },
{ "id": 62, "name": "Jacquelin", "place": "2 Butterfield Circle" },
{ "id": 63, "name": "Nolie", "place": "1834 Dixon Plaza" },
{ "id": 64, "name": "Leese", "place": "36029 Declaration Alley" },
{ "id": 65, "name": "Bartolomeo", "place": "617 Arrowood Lane" },
{ "id": 66, "name": "Rochette", "place": "894 Paget Terrace" },
{ "id": 67, "name": "Allyce", "place": "59 Dayton Pass" },
{ "id": 68, "name": "Dorelia", "place": "6182 Judy Court" },
{ "id": 69, "name": "Ranee", "place": "277 Westport Point" },
{ "id": 70, "name": "Gwenni", "place": "9662 Darwin Center" },
{ "id": 71, "name": "Rosina", "place": "42 Eastlawn Point" },
{ "id": 72, "name": "Alvinia", "place": "8 2nd Park" },
{ "id": 73, "name": "Cammy", "place": "0 Harbort Terrace" },
{ "id": 74, "name": "Bertha", "place": "7 Basil Drive" },
{ "id": 75, "name": "Lilian", "place": "4 Prairie Rose Park" },
{ "id": 76, "name": "Craggie", "place": "8689 Killdeer Avenue" },
{ "id": 77, "name": "Gregoire", "place": "8 Esch Point" },
{ "id": 78, "name": "Rhody", "place": "460 Maple Hill" },
{ "id": 79, "name": "Tiebold", "place": "1137 Dexter Avenue" },
{ "id": 80, "name": "Shani", "place": "1455 Eastlawn Trail" },
{ "id": 81, "name": "Davey", "place": "7615 Columbus Drive" },
{ "id": 82, "name": "Elsbeth", "place": "94 Troy Drive" },
{ "id": 83, "name": "Jobi", "place": "92 Sugar Parkway" },
{ "id": 84, "name": "Jackie", "place": "77 Commercial Circle" },
{ "id": 85, "name": "Holden", "place": "104 Arizona Street" },
{ "id": 86, "name": "Mervin", "place": "44 Dunning Plaza" },
{ "id": 87, "name": "Nicolais", "place": "44 Vermont Parkway" },
{ "id": 88, "name": "Gus", "place": "12564 Mockingbird Terrace" },
{ "id": 89, "name": "Abram", "place": "0 Lakewood Gardens Point" },
{ "id": 90, "name": "Hall", "place": "7689 Loftsgordon Way" },
{ "id": 91, "name": "Mallorie", "place": "98125 Cardinal Alley" },
{ "id": 92, "name": "Sharity", "place": "31 Westridge Point" },
{ "id": 93, "name": "Aaren", "place": "13 Arrowood Way" },
{ "id": 94, "name": "Ambur", "place": "49 Spenser Court" },
{ "id": 95, "name": "Adriaens", "place": "6 2nd Drive" },
{ "id": 96, "name": "Goldie", "place": "9623 Haas Park" },
{ "id": 97, "name": "Gertrud", "place": "4978 Duke Pass" },
{ "id": 98, "name": "Corilla", "place": "577 Kim Avenue" },
{ "id": 99, "name": "Joanne", "place": "40674 Ohio Alley" },
{ "id": 100, "name": "Ennis", "place": "10365 Morningstar Street" },
{ "id": 101, "name": "Norri", "place": "3508 Kenwood Point" },
{ "id": 102, "name": "Aretha", "place": "374 Bluejay Hill" },
{ "id": 103, "name": "Robbi", "place": "863 Veith Junction" },
{ "id": 104, "name": "Shirl", "place": "88198 Marquette Center" },
{ "id": 105, "name": "Jocelin", "place": "86 Northwestern Way" },
{ "id": 106, "name": "Gerti", "place": "89637 Annamark Drive" },
{ "id": 107, "name": "Oates", "place": "3714 Dakota Lane" },
{ "id": 108, "name": "Prinz", "place": "04 Dryden Terrace" },
{ "id": 109, "name": "Roxi", "place": "9 Mendota Center" },
{ "id": 110, "name": "Chickie", "place": "96795 Springs Circle" },
{ "id": 111, "name": "Lucila", "place": "34356 Evergreen Alley" },
{ "id": 112, "name": "Gunar", "place": "1 Marcy Junction" },
{ "id": 113, "name": "Sissie", "place": "74072 Lukken Hill" },
{ "id": 114, "name": "Bertrand", "place": "716 Kings Avenue" },
{ "id": 115, "name": "Gwendolin", "place": "7860 Mallard Parkway" },
{ "id": 116, "name": "La verne", "place": "82123 Brentwood Plaza" },
{ "id": 117, "name": "Rickie", "place": "59534 Cordelia Pass" },
{ "id": 118, "name": "Stesha", "place": "2147 Mayfield Drive" },
{ "id": 119, "name": "Gabriell", "place": "33 Darwin Crossing" },
{ "id": 120, "name": "Candide", "place": "24449 Cherokee Court" },
{ "id": 121, "name": "Rodger", "place": "822 Sunnyside Alley" },
{ "id": 122, "name": "Dode", "place": "24 Elmside Pass" },
{ "id": 123, "name": "Rowe", "place": "2473 Dawn Park" },
{ "id": 124, "name": "Kevan", "place": "14 Vera Court" },
{ "id": 125, "name": "Maxi", "place": "91795 Manufacturers Trail" },
{ "id": 126, "name": "Lia", "place": "7651 Mosinee Avenue" },
{ "id": 127, "name": "Had", "place": "08 Ilene Trail" },
{ "id": 128, "name": "Giselbert", "place": "284 Monica Street" },
{ "id": 129, "name": "Sena", "place": "32988 Nancy Drive" },
{ "id": 130, "name": "Stesha", "place": "3 Bartelt Plaza" },
{ "id": 131, "name": "Den", "place": "0 Westend Parkway" },
{ "id": 132, "name": "Willie", "place": "0 Shelley Park" },
{ "id": 133, "name": "Ingelbert", "place": "2679 Glacier Hill Alley" },
{ "id": 134, "name": "Susann", "place": "1764 Lukken Terrace" },
{ "id": 135, "name": "Vaughan", "place": "35772 Grayhawk Street" },
{ "id": 136, "name": "Monica", "place": "4 Starling Park" },
{ "id": 137, "name": "Lemmie", "place": "346 Elmside Court" },
{ "id": 138, "name": "Martainn", "place": "1030 Gateway Court" },
{ "id": 139, "name": "Rita", "place": "46201 Reinke Alley" },
{ "id": 140, "name": "Delilah", "place": "33662 Forest Center" },
{ "id": 141, "name": "Kennedy", "place": "28 Roxbury Center" },
{ "id": 142, "name": "Eustace", "place": "594 Stephen Court" },
{ "id": 143, "name": "Freedman", "place": "93121 Sunbrook Circle" },
{ "id": 144, "name": "Minni", "place": "10 3rd Circle" },
{ "id": 145, "name": "Norris", "place": "5342 Warrior Way" },
{ "id": 146, "name": "Darell", "place": "97 Springs Junction" },
{ "id": 147, "name": "Giraud", "place": "8 Brown Plaza" },
{ "id": 148, "name": "Randall", "place": "0195 Thompson Crossing" },
{ "id": 149, "name": "Dean", "place": "5670 Lukken Court" },
{ "id": 150, "name": "Tiffy", "place": "43 Summerview Pass" },
{ "id": 151, "name": "Hashim", "place": "46 Vermont Court" },
{ "id": 152, "name": "Sophronia", "place": "62 Green Pass" },
{ "id": 153, "name": "Talyah", "place": "805 Esker Plaza" },
{ "id": 154, "name": "Binky", "place": "4 Bonner Court" },
{ "id": 155, "name": "Jillayne", "place": "6844 Maple Street" },
{ "id": 156, "name": "Porty", "place": "1101 Hintze Park" },
{ "id": 157, "name": "Berky", "place": "99 Hallows Hill" },
{ "id": 158, "name": "Kiel", "place": "5 Armistice Junction" },
{ "id": 159, "name": "Engracia", "place": "08 Bobwhite Road" },
{ "id": 160, "name": "Jocko", "place": "1836 Jenna Junction" },
{ "id": 161, "name": "Gearalt", "place": "889 Kingsford Crossing" },
{ "id": 162, "name": "Mareah", "place": "6 Gulseth Plaza" },
{ "id": 163, "name": "Scotti", "place": "027 Nelson Court" },
{ "id": 164, "name": "Ingrid", "place": "5729 Briar Crest Lane" },
{ "id": 165, "name": "Tynan", "place": "98 Sutteridge Court" },
{ "id": 166, "name": "Buddy", "place": "020 Pepper Wood Court" },
{ "id": 167, "name": "Llywellyn", "place": "231 Melody Place" },
{ "id": 168, "name": "Rudolfo", "place": "36 Truax Drive" },
{ "id": 169, "name": "Bald", "place": "8831 Myrtle Crossing" },
{ "id": 170, "name": "Fawnia", "place": "93837 Grasskamp Plaza" },
{ "id": 171, "name": "Jelene", "place": "7 Ronald Regan Drive" },
{ "id": 172, "name": "Chaddy", "place": "2 Namekagon Alley" },
{ "id": 173, "name": "Kelly", "place": "873 Nova Avenue" },
{ "id": 174, "name": "Garland", "place": "14 Laurel Trail" },
{ "id": 175, "name": "Thurstan", "place": "4 Barby Trail" },
{ "id": 176, "name": "Nicolais", "place": "500 Northfield Point" },
{ "id": 177, "name": "Claudie", "place": "05 Donald Avenue" },
{ "id": 178, "name": "Constancia", "place": "6099 Leroy Way" },
{ "id": 179, "name": "Orland", "place": "5519 Truax Junction" },
{ "id": 180, "name": "Dody", "place": "3663 Porter Hill" },
{ "id": 181, "name": "Katheryn", "place": "2797 Mccormick Park" },
{ "id": 182, "name": "Pebrook", "place": "14 Hoepker Court" },
{ "id": 183, "name": "Oliviero", "place": "35 Rutledge Plaza" },
{ "id": 184, "name": "Ladonna", "place": "03653 Shelley Center" },
{ "id": 185, "name": "Lin", "place": "62447 Summer Ridge Plaza" },
{ "id": 186, "name": "Harrie", "place": "99 Westridge Road" },
{ "id": 187, "name": "King", "place": "154 Elgar Drive" },
{ "id": 188, "name": "Zorine", "place": "43 Pankratz Terrace" },
{ "id": 189, "name": "Bonnee", "place": "2532 Granby Parkway" },
{ "id": 190, "name": "Samaria", "place": "0778 Jenna Lane" },
{ "id": 191, "name": "Stewart", "place": "1625 Rieder Plaza" },
{ "id": 192, "name": "Diann", "place": "3154 Kings Lane" },
{ "id": 193, "name": "Armand", "place": "81401 Lighthouse Bay Crossing" },
{ "id": 194, "name": "Earle", "place": "5 Eagan Park" },
{ "id": 195, "name": "Bradly", "place": "47869 Dapin Place" },
{ "id": 196, "name": "Selia", "place": "3 6th Drive" },
{ "id": 197, "name": "Lona", "place": "412 Kensington Park" },
{ "id": 198, "name": "Josias", "place": "3 Elka Center" },
{ "id": 199, "name": "Marielle", "place": "04713 Merchant Parkway" },
{ "id": 200, "name": "Orton", "place": "2 Vernon Court" }]



const PORT = 4000;

const server = http.createServer((req, res) => {
    const url = req.url;

    if (url.includes("getPaginatedUsers")) {
        let str = url.split("?")[1];
        let pageNumber = parseInt(str.split("&")[0].split("=")[1]);
        let count = parseInt(str.split("&")[1].split("=")[1]);

        let startIndex = (pageNumber - 1) * count;
        let endIndex = startIndex + count;

        let paginatedUsers = users.slice(startIndex, endIndex);


        res.end(JSON.stringify(paginatedUsers));
    }
    else {
        res.end(`invalid input`)
    }
});

server.listen(PORT, (err) => {
    if (err) {
        console.log("Error", err)
    } else {
        console.log(`Server running at http://localhost:${PORT}/getPaginatedUsers?pageNumber=1&count=10`);
    }



});
